theme: jekyll-theme-cayman

# template: jekyll-theme-theme_name
# possible theme_name variables: architect / cayman / dinky / hacker leap_day / merlot / midnight / minima 
# / minimal  / modernist / slate / tactile / time_machine